development: 
  cloud_name: "victorbarh"
  api_key: "893546862154776"
  api_secret: "Oko75CZQLY6h26gRTpGF1AawQlc"
  gmail_username: "vistapaterner@gmail.com"
  gmail_password: "sggh syxf qofj ewli"
  GITHUB_CLIENT_ID: "Ov23liMsmyAogQJIEA0s"
  GITHUB_CLIENT_SECRET: "59f541459d1dfc42a9b17dbbe829e77164c9e8e4"
  REDIS_URL: "localhost"
  REDIS_PORT: "6379"
  POSTGRES_HOST: "localhost"
  POSTGRES_PORT: "5432"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "password"

production:
  cloud_name: "victorbarh"
  api_key: "893546862154776"
  api_secret: "Oko75CZQLY6h26gRTpGF1AawQlc"
  PINDO_API_KEY: "eyJhbGciOiJIUzUxMiJ9.eyJpZCI6InVzZXJfMDFIRTJYME5HMUFDWlk3UTlZNVdHMUhBUUYiLCJyZXZva2VkX3Rva2VuX2NvdW50IjoyLCJpYXQiOjE3Mjg4OTMxNzMsImV4cCI6MTgyMzUwMTE3M30.ig-ti5nEKYnX_44AMiM79GlrfrJM1mgFcBZYhKUHfmeXcMOi-OtBvlVHDMWomUDe-aiHT0K341t43oByGTw0Kg"
  gmail_username: "vistapaterner@gmail.com"
  gmail_password: "sggh syxf qofj ewli"
  GITHUB_CLIENT_ID: "Ov23liMsmyAogQJIEA0s"
  GITHUB_CLIENT_SECRET: "59f541459d1dfc42a9b17dbbe829e77164c9e8e4"
  REDIS_URL: "redis-11112.c240.us-east-1-3.ec2.cloud.redislabs.com"
  REDIS_PORT: "11112"
  REDIS_PASSWORD: "0XqwZroeqkNg1sYV9OWsya22MpYWNjt2"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "password"
  