development: 
  REDIS_URL: "redis://localhost:6379"
  REDIS_PORT: "6379"
  POSTGRES_HOST: "localhost"
  POSTGRES_PORT: "5432"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "password"
  AWS_ACCESS_KEY: "AKIAJZJZ"
  AWS_SECRET: "2weerthrtht"
  AWS_REGION: "us-east-1"