
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV["POSTGRES_HOST"] %>
  port: <%= ENV["POSTGRES_PORT"] %>
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>

development:
  <<: *default
  database: fluentpet_backend_development


test:
  <<: *default
  database: fluentpet_backend_test

production:
  primary: &primary_production
    <<: *default
    database: fluentpet_backend_production
    username: fluentpet_backend
    password: <%= ENV["FLUENTPET_BACKEND_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: fluentpet_backend_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: fluentpet_backend_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: fluentpet_backend_production_cable
    migrations_paths: db/cable_migrate
